run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/sarchlab/m2sim

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
